
import { Country } from './types';

// A curated list of countries for the dropdowns with currency codes and visual colors
export const COUNTRIES: Country[] = [
  { code: 'SA', nameAr: 'المملكة العربية السعودية', nameEn: 'Saudi Arabia', flag: '🇸🇦', currencyCode: 'SAR', color: '#165d31' },
  { code: 'AE', nameAr: 'الإمارات العربية المتحدة', nameEn: 'United Arab Emirates', flag: '🇦🇪', currencyCode: 'AED', color: '#00732f' },
  { code: 'EG', nameAr: 'مصر', nameEn: 'Egypt', flag: '🇪🇬', currencyCode: 'EGP', color: '#ce1126' },
  { code: 'US', nameAr: 'الولايات المتحدة الأمريكية', nameEn: 'United States', flag: '🇺🇸', currencyCode: 'USD', color: '#3c3b6e' },
  { code: 'GB', nameAr: 'المملكة المتحدة', nameEn: 'United Kingdom', flag: '🇬🇧', currencyCode: 'GBP', color: '#012169' },
  { code: 'CA', nameAr: 'كندا', nameEn: 'Canada', flag: '🇨🇦', currencyCode: 'CAD', color: '#d80621' },
  { code: 'FR', nameAr: 'فرنسا', nameEn: 'France', flag: '🇫🇷', currencyCode: 'EUR', color: '#0055a4' },
  { code: 'DE', nameAr: 'ألمانيا', nameEn: 'Germany', flag: '🇩🇪', currencyCode: 'EUR', color: '#dd0000' },
  { code: 'IT', nameAr: 'إيطاليا', nameEn: 'Italy', flag: '🇮🇹', currencyCode: 'EUR', color: '#008c45' },
  { code: 'ES', nameAr: 'إسبانيا', nameEn: 'Spain', flag: '🇪🇸', currencyCode: 'EUR', color: '#aa151b' },
  { code: 'TR', nameAr: 'تركيا', nameEn: 'Turkey', flag: '🇹🇷', currencyCode: 'TRY', color: '#e30a17' },
  { code: 'JP', nameAr: 'اليابان', nameEn: 'Japan', flag: '🇯🇵', currencyCode: 'JPY', color: '#bc002d' },
  { code: 'CN', nameAr: 'الصين', nameEn: 'China', flag: '🇨🇳', currencyCode: 'CNY', color: '#de2910' },
  { code: 'IN', nameAr: 'الهند', nameEn: 'India', flag: '🇮🇳', currencyCode: 'INR', color: '#ff9933' },
  { code: 'QA', nameAr: 'قطر', nameEn: 'Qatar', flag: '🇶🇦', currencyCode: 'QAR', color: '#8d1b3d' },
  { code: 'KW', nameAr: 'الكويت', nameEn: 'Kuwait', flag: '🇰🇼', currencyCode: 'KWD', color: '#007a3d' },
  { code: 'BH', nameAr: 'البحرين', nameEn: 'Bahrain', flag: '🇧🇭', currencyCode: 'BHD', color: '#ce1126' },
  { code: 'OM', nameAr: 'عمان', nameEn: 'Oman', flag: '🇴🇲', currencyCode: 'OMR', color: '#db161b' },
  { code: 'JO', nameAr: 'الأردن', nameEn: 'Jordan', flag: '🇯🇴', currencyCode: 'JOD', color: '#007a3d' },
  { code: 'LB', nameAr: 'لبنان', nameEn: 'Lebanon', flag: '🇱🇧', currencyCode: 'LBP', color: '#ed1c24' },
  { code: 'MA', nameAr: 'المغرب', nameEn: 'Morocco', flag: '🇲🇦', currencyCode: 'MAD', color: '#c1272d' },
  { code: 'DZ', nameAr: 'الجزائر', nameEn: 'Algeria', flag: '🇩🇿', currencyCode: 'DZD', color: '#006233' },
  { code: 'TN', nameAr: 'تونس', nameEn: 'Tunisia', flag: '🇹🇳', currencyCode: 'TND', color: '#e70013' },
  { code: 'MY', nameAr: 'ماليزيا', nameEn: 'Malaysia', flag: '🇲🇾', currencyCode: 'MYR', color: '#010066' },
  { code: 'ID', nameAr: 'إندونيسيا', nameEn: 'Indonesia', flag: '🇮🇩', currencyCode: 'IDR', color: '#ce1126' },
  { code: 'TH', nameAr: 'تايلاند', nameEn: 'Thailand', flag: '🇹🇭', currencyCode: 'THB', color: '#241d4f' },
  { code: 'SG', nameAr: 'سنغافورة', nameEn: 'Singapore', flag: '🇸🇬', currencyCode: 'SGD', color: '#ed2939' },
  { code: 'KR', nameAr: 'كوريا الجنوبية', nameEn: 'South Korea', flag: '🇰🇷', currencyCode: 'KRW', color: '#0f64cd' },
  { code: 'RU', nameAr: 'روسيا', nameEn: 'Russia', flag: '🇷🇺', currencyCode: 'RUB', color: '#0039a6' },
  { code: 'AU', nameAr: 'أستراليا', nameEn: 'Australia', flag: '🇦🇺', currencyCode: 'AUD', color: '#00008b' },
  { code: 'BR', nameAr: 'البرازيل', nameEn: 'Brazil', flag: '🇧🇷', currencyCode: 'BRL', color: '#009c3b' },
  { code: 'ZA', nameAr: 'جنوب أفريقيا', nameEn: 'South Africa', flag: '🇿🇦', currencyCode: 'ZAR', color: '#007749' },
  { code: 'CH', nameAr: 'سويسرا', nameEn: 'Switzerland', flag: '🇨🇭', currencyCode: 'CHF', color: '#d52b1e' },
  { code: 'NL', nameAr: 'هولندا', nameEn: 'Netherlands', flag: '🇳🇱', currencyCode: 'EUR', color: '#21468b' },
  { code: 'SE', nameAr: 'السويد', nameEn: 'Sweden', flag: '🇸🇪', currencyCode: 'SEK', color: '#006aa7' },
  { code: 'NO', nameAr: 'النرويج', nameEn: 'Norway', flag: '🇳🇴', currencyCode: 'NOK', color: '#ba0c2f' },
  { code: 'DK', nameAr: 'الدانمارك', nameEn: 'Denmark', flag: '🇩🇰', currencyCode: 'DKK', color: '#c60c30' },
  { code: 'PT', nameAr: 'البرتغال', nameEn: 'Portugal', flag: '🇵🇹', currencyCode: 'EUR', color: '#006600' },
  { code: 'GR', nameAr: 'اليونان', nameEn: 'Greece', flag: '🇬🇷', currencyCode: 'EUR', color: '#0d5eaf' },
  { code: 'AT', nameAr: 'النمسا', nameEn: 'Austria', flag: '🇦🇹', currencyCode: 'EUR', color: '#ed2939' },
  { code: 'BE', nameAr: 'بلجيكا', nameEn: 'Belgium', flag: '🇧🇪', currencyCode: 'EUR', color: '#000000' },
  { code: 'CZ', nameAr: 'التشيك', nameEn: 'Czech Republic', flag: '🇨🇿', currencyCode: 'CZK', color: '#11457e' },
  { code: 'HU', nameAr: 'المجر', nameEn: 'Hungary', flag: '🇭🇺', currencyCode: 'HUF', color: '#436f4d' },
  { code: 'FI', nameAr: 'فنلندا', nameEn: 'Finland', flag: '🇫🇮', currencyCode: 'EUR', color: '#003580' },
  { code: 'RO', nameAr: 'رومانيا', nameEn: 'Romania', flag: '🇷🇴', currencyCode: 'RON', color: '#002b7f' },
  { code: 'CY', nameAr: 'قبرص', nameEn: 'Cyprus', flag: '🇨🇾', currencyCode: 'EUR', color: '#d57800' },
  { code: 'MT', nameAr: 'مالطا', nameEn: 'Malta', flag: '🇲🇹', currencyCode: 'EUR', color: '#bf0024' },
  { code: 'IS', nameAr: 'أيسلندا', nameEn: 'Iceland', flag: '🇮🇸', currencyCode: 'ISK', color: '#02529c' },
  { code: 'RS', nameAr: 'صربيا', nameEn: 'Serbia', flag: '🇷🇸', currencyCode: 'RSD', color: '#c6363c' },
  { code: 'BA', nameAr: 'البوسنة والهرسك', nameEn: 'Bosnia and Herzegovina', flag: '🇧🇦', currencyCode: 'BAM', color: '#002395' },
  { code: 'UZ', nameAr: 'أوزبكستان', nameEn: 'Uzbekistan', flag: '🇺🇿', currencyCode: 'UZS', color: '#0099b5' },
  { code: 'KZ', nameAr: 'كازاخستان', nameEn: 'Kazakhstan', flag: '🇰🇿', currencyCode: 'KZT', color: '#00afca' },
  { code: 'MV', nameAr: 'المالديف', nameEn: 'Maldives', flag: '🇲🇻', currencyCode: 'MVR', color: '#d11231' },
  { code: 'GE', nameAr: 'جورجيا', nameEn: 'Georgia', flag: '🇬🇪', currencyCode: 'GEL', color: '#ff0000' },
  { code: 'AZ', nameAr: 'أذربيجان', nameEn: 'Azerbaijan', flag: '🇦🇿', currencyCode: 'AZN', color: '#00b5e2' },
  { code: 'AM', nameAr: 'أرمينيا', nameEn: 'Armenia', flag: '🇦🇲', currencyCode: 'AMD', color: '#d90012' },
  { code: 'LK', nameAr: 'سريلانكا', nameEn: 'Sri Lanka', flag: '🇱🇰', currencyCode: 'LKR', color: '#8d153a' },
  { code: 'PH', nameAr: 'الفلبين', nameEn: 'Philippines', flag: '🇵🇭', currencyCode: 'PHP', color: '#0038a8' },
  { code: 'VN', nameAr: 'فيتنام', nameEn: 'Vietnam', flag: '🇻🇳', currencyCode: 'VND', color: '#da251d' },
  { code: 'MX', nameAr: 'المكسيك', nameEn: 'Mexico', flag: '🇲🇽', currencyCode: 'MXN', color: '#006847' },
  { code: 'AR', nameAr: 'الأرجنتين', nameEn: 'Argentina', flag: '🇦🇷', currencyCode: 'ARS', color: '#75aadb' },
  { code: 'NZ', nameAr: 'نيوزيلندا', nameEn: 'New Zealand', flag: '🇳🇿', currencyCode: 'NZD', color: '#00247d' },
  { code: 'PK', nameAr: 'باكستان', nameEn: 'Pakistan', flag: '🇵🇰', currencyCode: 'PKR', color: '#115740' },
  { code: 'BD', nameAr: 'بنغلاديش', nameEn: 'Bangladesh', flag: '🇧🇩', currencyCode: 'BDT', color: '#006a4e' },
  { code: 'NG', nameAr: 'نيجيريا', nameEn: 'Nigeria', flag: '🇳🇬', currencyCode: 'NGN', color: '#008751' },
  { code: 'PL', nameAr: 'بولندا', nameEn: 'Poland', flag: '🇵🇱', currencyCode: 'PLN', color: '#dc143c' },
  { code: 'UA', nameAr: 'أوكرانيا', nameEn: 'Ukraine', flag: '🇺🇦', currencyCode: 'UAH', color: '#0057b7' },
  { code: 'IE', nameAr: 'أيرلندا', nameEn: 'Ireland', flag: '🇮🇪', currencyCode: 'EUR', color: '#169b62' },
  { code: 'HR', nameAr: 'كرواتيا', nameEn: 'Croatia', flag: '🇭🇷', currencyCode: 'EUR', color: '#ff0000' },
  { code: 'BG', nameAr: 'بلغاريا', nameEn: 'Bulgaria', flag: '🇧🇬', currencyCode: 'BGN', color: '#00966e' },
  { code: 'RW', nameAr: 'رواندا', nameEn: 'Rwanda', flag: '🇷🇼', currencyCode: 'RWF', color: '#00a1de' },
  { code: 'KE', nameAr: 'كينيا', nameEn: 'Kenya', flag: '🇰🇪', currencyCode: 'KES', color: '#000000' },
  { code: 'AL', nameAr: 'ألبانيا', nameEn: 'Albania', flag: '🇦🇱', currencyCode: 'ALL', color: '#e41e20' },
  { code: 'CR', nameAr: 'كوستاريكا', nameEn: 'Costa Rica', flag: '🇨🇷', currencyCode: 'CRC', color: '#002b7f' },
  { code: 'PA', nameAr: 'بنما', nameEn: 'Panama', flag: '🇵🇦', currencyCode: 'USD', color: '#005293' },
  { code: 'BZ', nameAr: 'بليز', nameEn: 'Belize', flag: '🇧🇿', currencyCode: 'BZD', color: '#003f87' },
  { code: 'SV', nameAr: 'السلفادور', nameEn: 'El Salvador', flag: '🇸🇻', currencyCode: 'USD', color: '#0047ab' },
  { code: 'GT', nameAr: 'غواتيمالا', nameEn: 'Guatemala', flag: '🇬🇹', currencyCode: 'GTQ', color: '#4997d0' },
  { code: 'HN', nameAr: 'هندوراس', nameEn: 'Honduras', flag: '🇭🇳', currencyCode: 'HNL', color: '#0073cf' },
  { code: 'DO', nameAr: 'جمهورية الدومينيكان', nameEn: 'Dominican Republic', flag: '🇩🇴', currencyCode: 'DOP', color: '#002d62' },
  { code: 'BM', nameAr: 'برمودا', nameEn: 'Bermuda', flag: '🇧🇲', currencyCode: 'BMD', color: '#ee2d24' },
  { code: 'AG', nameAr: 'أنتيغوا وبربودا', nameEn: 'Antigua and Barbuda', flag: '🇦🇬', currencyCode: 'XCD', color: '#ce1126' },
  { code: 'ME', nameAr: 'الجبل الأسود', nameEn: 'Montenegro', flag: '🇲🇪', currencyCode: 'EUR', color: '#c40308' },
  { code: 'MK', nameAr: 'مقدونيا الشمالية', nameEn: 'North Macedonia', flag: '🇲🇰', currencyCode: 'MKD', color: '#d20000' },
  { code: 'HK', nameAr: 'هونغ كونغ', nameEn: 'Hong Kong', flag: '🇭🇰', currencyCode: 'HKD', color: '#de2910' },
  { code: 'CO', nameAr: 'كولومبيا', nameEn: 'Colombia', flag: '🇨🇴', currencyCode: 'COP', color: '#fcd116' },
  { code: 'NP', nameAr: 'نيبال', nameEn: 'Nepal', flag: '🇳🇵', currencyCode: 'NPR', color: '#dc143c' },
  { code: 'TZ', nameAr: 'تنزانيا', nameEn: 'Tanzania', flag: '🇹🇿', currencyCode: 'TZS', color: '#1eb53a' },
  { code: 'SC', nameAr: 'سيشيل', nameEn: 'Seychelles', flag: '🇸🇨', currencyCode: 'SCR', color: '#003d88' },
  { code: 'MU', nameAr: 'موريشيوس', nameEn: 'Mauritius', flag: '🇲🇺', currencyCode: 'MUR', color: '#ea2839' },
].sort((a, b) => a.nameAr.localeCompare(b.nameAr));

// Approximate Exchange Rates relative to 1 USD (Static data for tool)
export const EXCHANGE_RATES: Record<string, number> = {
  'USD': 1,
  'EUR': 0.92,
  'GBP': 0.78,
  'SAR': 3.75,
  'AED': 3.67,
  'EGP': 49.5,
  'TRY': 34.2,
  'JPY': 152,
  'CNY': 7.2,
  'INR': 84.4,
  'QAR': 3.64,
  'KWD': 0.31,
  'BHD': 0.38,
  'OMR': 0.385,
  'JOD': 0.71,
  'LBP': 89500,
  'MAD': 10.1,
  'DZD': 134,
  'TND': 3.1,
  'MYR': 4.4,
  'IDR': 15700,
  'THB': 34.5,
  'SGD': 1.33,
  'KRW': 1380,
  'RUB': 97,
  'CAD': 1.39,
  'AUD': 1.52,
  'BRL': 5.75,
  'ZAR': 17.8,
  'CHF': 0.88,
  'SEK': 10.8,
  'NOK': 11.0,
  'DKK': 6.9,
  'MVR': 15.4,
  'GEL': 2.72,
  'AZN': 1.7,
  'AMD': 387,
  'LKR': 293,
  'PHP': 58,
  'VND': 25300,
  'MXN': 20.2,
  'ARS': 990,
  'NZD': 1.67,
  'PKR': 278,
  'BDT': 120,
  'NGN': 1650,
  'PLN': 4.05,
  'UAH': 41.3,
  'ALL': 92.5,
  'RWF': 1360,
  'KES': 129,
  'BGN': 1.8,
  'CRC': 505,
  'BZD': 2.0,
  'GTQ': 7.7,
  'HNL': 24.7,
  'DOP': 59.0,
  'BMD': 1.0,
  'XCD': 2.7,
  'MKD': 56.5,
  'CZK': 23.5,
  'HUF': 370,
  'RON': 4.6,
  'ISK': 137,
  'RSD': 117,
  'BAM': 1.8,
  'UZS': 12600,
  'KZT': 450,
  'HKD': 7.8,
  'TWD': 32.5,
  'COP': 4400,
  'PEN': 3.75,
  'CLP': 980,
  'NPR': 135,
  'TZS': 2600,
  'SCR': 13.5,
  'MUR': 46.5
};
